name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image #docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: |
        pip install -r requirements.txt
        docker build -t furniture-detection-app . 
        docker run -p 80:80 furniture-detection-app
